package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Demographics")
   private com.rh.demo.bpm.applicationmanagement.model.Demographics demographics;

   @org.kie.api.definition.type.Label("Address")
   private java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address;

   @org.kie.api.definition.type.Label("Email")
   private com.rh.demo.bpm.applicationmanagement.model.Email email;

   @org.kie.api.definition.type.Label("Phone")
   private com.rh.demo.bpm.applicationmanagement.model.Phone phone;

   @org.kie.api.definition.type.Label("FinancialInformation")
   private com.rh.demo.bpm.applicationmanagement.model.FinancialInformation financialInformation;

   @org.kie.api.definition.type.Label("EmploymentDetails")
   private java.util.List<com.rh.demo.bpm.applicationmanagement.model.EmploymentDetails> employmentDetails;

   @org.kie.api.definition.type.Label("personalDetails")
   private com.rh.demo.bpm.applicationmanagement.model.PersonalDetails personalDetails;

   public Application()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Demographics getDemographics()
   {
      return this.demographics;
   }

   public void setDemographics(
         com.rh.demo.bpm.applicationmanagement.model.Demographics demographics)
   {
      this.demographics = demographics;
   }

   public java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> getAddress()
   {
      return this.address;
   }

   public void setAddress(
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address)
   {
      this.address = address;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Email getEmail()
   {
      return this.email;
   }

   public void setEmail(com.rh.demo.bpm.applicationmanagement.model.Email email)
   {
      this.email = email;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Phone getPhone()
   {
      return this.phone;
   }

   public void setPhone(com.rh.demo.bpm.applicationmanagement.model.Phone phone)
   {
      this.phone = phone;
   }

   public com.rh.demo.bpm.applicationmanagement.model.FinancialInformation getFinancialInformation()
   {
      return this.financialInformation;
   }

   public void setFinancialInformation(
         com.rh.demo.bpm.applicationmanagement.model.FinancialInformation financialInformation)
   {
      this.financialInformation = financialInformation;
   }

   public java.util.List<com.rh.demo.bpm.applicationmanagement.model.EmploymentDetails> getEmploymentDetails()
   {
      return this.employmentDetails;
   }

   public void setEmploymentDetails(
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.EmploymentDetails> employmentDetails)
   {
      this.employmentDetails = employmentDetails;
   }

   public com.rh.demo.bpm.applicationmanagement.model.PersonalDetails getPersonalDetails()
   {
      return this.personalDetails;
   }

   public void setPersonalDetails(
         com.rh.demo.bpm.applicationmanagement.model.PersonalDetails personalDetails)
   {
      this.personalDetails = personalDetails;
   }

   public Application(
         java.lang.Long id,
         com.rh.demo.bpm.applicationmanagement.model.Demographics demographics,
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address,
         com.rh.demo.bpm.applicationmanagement.model.Email email,
         com.rh.demo.bpm.applicationmanagement.model.Phone phone,
         com.rh.demo.bpm.applicationmanagement.model.FinancialInformation financialInformation,
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.EmploymentDetails> employmentDetails,
         com.rh.demo.bpm.applicationmanagement.model.PersonalDetails personalDetails)
   {
      this.id = id;
      this.demographics = demographics;
      this.address = address;
      this.email = email;
      this.phone = phone;
      this.financialInformation = financialInformation;
      this.employmentDetails = employmentDetails;
      this.personalDetails = personalDetails;
   }

}
