package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CompanyDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;

   @org.kie.api.definition.type.Label("CompanyName")
   private java.lang.String companyName;

   @org.kie.api.definition.type.Label("TradingYears")
   private java.lang.Integer tradingYears;

   @org.kie.api.definition.type.Label("DunsNumber")
   private java.lang.Integer dunsNumber;

   public CompanyDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCompanyName()
   {
      return this.companyName;
   }

   public void setCompanyName(java.lang.String companyName)
   {
      this.companyName = companyName;
   }

   public java.lang.Integer getTradingYears()
   {
      return this.tradingYears;
   }

   public void setTradingYears(java.lang.Integer tradingYears)
   {
      this.tradingYears = tradingYears;
   }

   public java.lang.Integer getDunsNumber()
   {
      return this.dunsNumber;
   }

   public void setDunsNumber(java.lang.Integer dunsNumber)
   {
      this.dunsNumber = dunsNumber;
   }

   public CompanyDetails(java.lang.Long id, java.lang.String companyName,
         java.lang.Integer tradingYears, java.lang.Integer dunsNumber)
   {
      this.id = id;
      this.companyName = companyName;
      this.tradingYears = tradingYears;
      this.dunsNumber = dunsNumber;
   }

}
