package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Demographics implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DEMOGRAPHICS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "DEMOGRAPHICS_ID_GENERATOR", sequenceName = "DEMOGRAPHICS_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Gender")
   private java.lang.String gender;

   @org.kie.api.definition.type.Label("DateOfBirth")
   private java.util.Date dateOfBirth;

   @org.kie.api.definition.type.Label("BirthPlace")
   private java.lang.String birthPlace;

   @org.kie.api.definition.type.Label("CountryOfBirth")
   private java.lang.String countryOfBirth;

   @org.kie.api.definition.type.Label("Nationality")
   private java.lang.String nationality;

   public Demographics()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.util.Date getDateOfBirth()
   {
      return this.dateOfBirth;
   }

   public void setDateOfBirth(java.util.Date dateOfBirth)
   {
      this.dateOfBirth = dateOfBirth;
   }

   public java.lang.String getBirthPlace()
   {
      return this.birthPlace;
   }

   public void setBirthPlace(java.lang.String birthPlace)
   {
      this.birthPlace = birthPlace;
   }

   public java.lang.String getCountryOfBirth()
   {
      return this.countryOfBirth;
   }

   public void setCountryOfBirth(java.lang.String countryOfBirth)
   {
      this.countryOfBirth = countryOfBirth;
   }

   public java.lang.String getNationality()
   {
      return this.nationality;
   }

   public void setNationality(java.lang.String nationality)
   {
      this.nationality = nationality;
   }

   public Demographics(java.lang.Long id, java.lang.String gender,
         java.util.Date dateOfBirth, java.lang.String birthPlace,
         java.lang.String countryOfBirth, java.lang.String nationality)
   {
      this.id = id;
      this.gender = gender;
      this.dateOfBirth = dateOfBirth;
      this.birthPlace = birthPlace;
      this.countryOfBirth = countryOfBirth;
      this.nationality = nationality;
   }

}