package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */


public class Email implements java.io.Serializable
{

   static final long serialVersionUID = 1L;


   private java.lang.Long id;

   @org.kie.api.definition.type.Label("EmailAddress")
   private java.lang.String emailAddress;

   @org.kie.api.definition.type.Label("OkToEmail")
   private java.lang.String okToEmail;

   public Email()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getEmailAddress()
   {
      return this.emailAddress;
   }

   public void setEmailAddress(java.lang.String emailAddress)
   {
      this.emailAddress = emailAddress;
   }

   public java.lang.String getOkToEmail()
   {
      return this.okToEmail;
   }

   public void setOkToEmail(java.lang.String okToEmail)
   {
      this.okToEmail = okToEmail;
   }

   public Email(java.lang.Long id, java.lang.String emailAddress,
         java.lang.String okToEmail)
   {
      this.id = id;
      this.emailAddress = emailAddress;
      this.okToEmail = okToEmail;
   }

}