package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class EmploymentDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPLOYMENTDETAILS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "EMPLOYMENTDETAILS_ID_GENERATOR", sequenceName = "EMPLOYMENTDETAILS_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("EmployerName")
   private java.lang.String employerName;

   @org.kie.api.definition.type.Label("JobTitle")
   private java.lang.String jobTitle;

   @org.kie.api.definition.type.Label("EmploymentStatus")
   private java.lang.String employmentStatus;

   @org.kie.api.definition.type.Label(value = "EmploymentDurationInYears")
   private java.lang.Integer employmentDurationInYears;

   public EmploymentDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getEmployerName()
   {
      return this.employerName;
   }

   public void setEmployerName(java.lang.String employerName)
   {
      this.employerName = employerName;
   }

   public java.lang.String getJobTitle()
   {
      return this.jobTitle;
   }

   public void setJobTitle(java.lang.String jobTitle)
   {
      this.jobTitle = jobTitle;
   }

   public java.lang.String getEmploymentStatus()
   {
      return this.employmentStatus;
   }

   public void setEmploymentStatus(java.lang.String employmentStatus)
   {
      this.employmentStatus = employmentStatus;
   }

   public java.lang.Integer getEmploymentDurationInYears()
   {
      return this.employmentDurationInYears;
   }

   public void setEmploymentDurationInYears(
         java.lang.Integer employmentDurationInYears)
   {
      this.employmentDurationInYears = employmentDurationInYears;
   }

   public EmploymentDetails(java.lang.Long id, java.lang.String employerName,
         java.lang.String jobTitle, java.lang.String employmentStatus,
         java.lang.Integer employmentDurationInYears)
   {
      this.id = id;
      this.employerName = employerName;
      this.jobTitle = jobTitle;
      this.employmentStatus = employmentStatus;
      this.employmentDurationInYears = employmentDurationInYears;
   }

}