package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class existingLoanDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EXISTINGLOANDETAILS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "EXISTINGLOANDETAILS_ID_GENERATOR", sequenceName = "EXISTINGLOANDETAILS_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("LoanType")
   private java.lang.String loanType;

   @org.kie.api.definition.type.Label("MonthlyInstallmentAmount")
   private java.math.BigDecimal monthlyInstallmentAmount;

   @org.kie.api.definition.type.Label("OutstandingBalanceAmount")
   private java.math.BigDecimal outstandingBalanceAmount;

   @org.kie.api.definition.type.Label("DebtOwnership")
   private java.lang.String debtOwnership;

   @org.kie.api.definition.type.Label("LenderName")
   private java.lang.String lenderName;

   public existingLoanDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getLoanType()
   {
      return this.loanType;
   }

   public void setLoanType(java.lang.String loanType)
   {
      this.loanType = loanType;
   }

   public java.math.BigDecimal getMonthlyInstallmentAmount()
   {
      return this.monthlyInstallmentAmount;
   }

   public void setMonthlyInstallmentAmount(
         java.math.BigDecimal monthlyInstallmentAmount)
   {
      this.monthlyInstallmentAmount = monthlyInstallmentAmount;
   }

   public java.math.BigDecimal getOutstandingBalanceAmount()
   {
      return this.outstandingBalanceAmount;
   }

   public void setOutstandingBalanceAmount(
         java.math.BigDecimal outstandingBalanceAmount)
   {
      this.outstandingBalanceAmount = outstandingBalanceAmount;
   }

   public java.lang.String getDebtOwnership()
   {
      return this.debtOwnership;
   }

   public void setDebtOwnership(java.lang.String debtOwnership)
   {
      this.debtOwnership = debtOwnership;
   }

   public java.lang.String getLenderName()
   {
      return this.lenderName;
   }

   public void setLenderName(java.lang.String lenderName)
   {
      this.lenderName = lenderName;
   }

   public existingLoanDetails(java.lang.Long id, java.lang.String loanType,
         java.math.BigDecimal monthlyInstallmentAmount,
         java.math.BigDecimal outstandingBalanceAmount,
         java.lang.String debtOwnership, java.lang.String lenderName)
   {
      this.id = id;
      this.loanType = loanType;
      this.monthlyInstallmentAmount = monthlyInstallmentAmount;
      this.outstandingBalanceAmount = outstandingBalanceAmount;
      this.debtOwnership = debtOwnership;
      this.lenderName = lenderName;
   }

}