package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */


public class IncomeDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;


   private java.lang.Long id;

   private java.lang.String incomeType;

   private java.math.BigDecimal fixedAmount;

   private java.math.BigDecimal variableAmount;

   private java.lang.String frequency;

   private java.lang.String otherIncomeDescription;

   public IncomeDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getIncomeType()
   {
      return this.incomeType;
   }

   public void setIncomeType(java.lang.String incomeType)
   {
      this.incomeType = incomeType;
   }

   public java.math.BigDecimal getFixedAmount()
   {
      return this.fixedAmount;
   }

   public void setFixedAmount(java.math.BigDecimal fixedAmount)
   {
      this.fixedAmount = fixedAmount;
   }

   public java.math.BigDecimal getVariableAmount()
   {
      return this.variableAmount;
   }

   public void setVariableAmount(java.math.BigDecimal variableAmount)
   {
      this.variableAmount = variableAmount;
   }

   public java.lang.String getFrequency()
   {
      return this.frequency;
   }

   public void setFrequency(java.lang.String frequency)
   {
      this.frequency = frequency;
   }

   public java.lang.String getOtherIncomeDescription()
   {
      return this.otherIncomeDescription;
   }

   public void setOtherIncomeDescription(
         java.lang.String otherIncomeDescription)
   {
      this.otherIncomeDescription = otherIncomeDescription;
   }

   public IncomeDetails(java.lang.Long id, java.lang.String incomeType,
         java.math.BigDecimal fixedAmount,
         java.math.BigDecimal variableAmount, java.lang.String frequency,
         java.lang.String otherIncomeDescription)
   {
      this.id = id;
      this.incomeType = incomeType;
      this.fixedAmount = fixedAmount;
      this.variableAmount = variableAmount;
      this.frequency = frequency;
      this.otherIncomeDescription = otherIncomeDescription;
   }

}
