package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonalDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.rh.demo.bpm.applicationmanagement.model.Name name;
   private com.rh.demo.bpm.applicationmanagement.model.Demographics demographics;
   private java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address;
   private com.rh.demo.bpm.applicationmanagement.model.Email email;
   private com.rh.demo.bpm.applicationmanagement.model.Phone phone;

   public PersonalDetails()
   {
   }

   public com.rh.demo.bpm.applicationmanagement.model.Name getName()
   {
      return this.name;
   }

   public void setName(com.rh.demo.bpm.applicationmanagement.model.Name name)
   {
      this.name = name;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Demographics getDemographics()
   {
      return this.demographics;
   }

   public void setDemographics(
         com.rh.demo.bpm.applicationmanagement.model.Demographics demographics)
   {
      this.demographics = demographics;
   }

   public java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> getAddress()
   {
      return this.address;
   }

   public void setAddress(
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address)
   {
      this.address = address;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Email getEmail()
   {
      return this.email;
   }

   public void setEmail(com.rh.demo.bpm.applicationmanagement.model.Email email)
   {
      this.email = email;
   }

   public com.rh.demo.bpm.applicationmanagement.model.Phone getPhone()
   {
      return this.phone;
   }

   public void setPhone(com.rh.demo.bpm.applicationmanagement.model.Phone phone)
   {
      this.phone = phone;
   }

   public PersonalDetails(
         com.rh.demo.bpm.applicationmanagement.model.Name name,
         com.rh.demo.bpm.applicationmanagement.model.Demographics demographics,
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Address> address,
         com.rh.demo.bpm.applicationmanagement.model.Email email,
         com.rh.demo.bpm.applicationmanagement.model.Phone phone)
   {
      this.name = name;
      this.demographics = demographics;
      this.address = address;
      this.email = email;
      this.phone = phone;
   }

}
