package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Phone implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PHONE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PHONE_ID_GENERATOR", sequenceName = "PHONE_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "PhoneType")
   private java.lang.String phoneType;

   @org.kie.api.definition.type.Label(value = "PhoneCountryCode")
   private java.lang.String phoneCountryCode;

   @org.kie.api.definition.type.Label(value = "AreaCode")
   private java.lang.String areaCode;

   @org.kie.api.definition.type.Label(value = "PhoneNumber")
   private java.lang.String phoneNumber;

   @org.kie.api.definition.type.Label(value = "Extension")
   private java.lang.String extension;

   @org.kie.api.definition.type.Label(value = "OkToSMS")
   private java.lang.Boolean okToSMS;

   @org.kie.api.definition.type.Label(value = "OkToCall")
   private java.lang.Boolean okToCall;

   public Phone()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getPhoneType()
   {
      return this.phoneType;
   }

   public void setPhoneType(java.lang.String phoneType)
   {
      this.phoneType = phoneType;
   }

   public java.lang.String getPhoneCountryCode()
   {
      return this.phoneCountryCode;
   }

   public void setPhoneCountryCode(java.lang.String phoneCountryCode)
   {
      this.phoneCountryCode = phoneCountryCode;
   }

   public java.lang.String getAreaCode()
   {
      return this.areaCode;
   }

   public void setAreaCode(java.lang.String areaCode)
   {
      this.areaCode = areaCode;
   }

   public java.lang.String getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.String getExtension()
   {
      return this.extension;
   }

   public void setExtension(java.lang.String extension)
   {
      this.extension = extension;
   }

   public java.lang.Boolean getOkToSMS()
   {
      return this.okToSMS;
   }

   public void setOkToSMS(java.lang.Boolean okToSMS)
   {
      this.okToSMS = okToSMS;
   }

   public java.lang.Boolean getOkToCall()
   {
      return this.okToCall;
   }

   public void setOkToCall(java.lang.Boolean okToCall)
   {
      this.okToCall = okToCall;
   }

   public Phone(java.lang.Long id, java.lang.String phoneType,
         java.lang.String phoneCountryCode, java.lang.String areaCode,
         java.lang.String phoneNumber, java.lang.String extension,
         java.lang.Boolean okToSMS, java.lang.Boolean okToCall)
   {
      this.id = id;
      this.phoneType = phoneType;
      this.phoneCountryCode = phoneCountryCode;
      this.areaCode = areaCode;
      this.phoneNumber = phoneNumber;
      this.extension = extension;
      this.okToSMS = okToSMS;
      this.okToCall = okToCall;
   }

}