package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Status implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;

   private java.lang.String status;

   private java.util.Date statusDate;

   public Status()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.util.Date getStatusDate()
   {
      return this.statusDate;
   }

   public void setStatusDate(java.util.Date statusDate)
   {
      this.statusDate = statusDate;
   }

   public Status(java.lang.Long id, java.lang.String status,
         java.util.Date statusDate)
   {
      this.id = id;
      this.status = status;
      this.statusDate = statusDate;
   }

}
