package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

<<<<<<< HEAD

=======
>>>>>>> d30c2ec4f5e95f9624604f3f7704bbeaf9debb54
public class StatusList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

<<<<<<< HEAD

   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Status")
=======
   @javax.persistence.GeneratedValue(generator = "STATUS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "STATUS_ID_GENERATOR", sequenceName = "STATUS_ID_SEQ")
   private java.lang.Long id;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("Status")
>>>>>>> d30c2ec4f5e95f9624604f3f7704bbeaf9debb54
   private java.util.List<com.rh.demo.bpm.applicationmanagement.model.Status> status;

   public StatusList()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.List<com.rh.demo.bpm.applicationmanagement.model.Status> getStatus()
   {
      return this.status;
   }

   public void setStatus(
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Status> status)
   {
      this.status = status;
   }

   public StatusList(
         java.lang.Long id,
         java.util.List<com.rh.demo.bpm.applicationmanagement.model.Status> status)
   {
      this.id = id;
      this.status = status;
   }

}