package com.rh.demo.bpm.applicationmanagement.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Status implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STATUS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "STATUS_ID_GENERATOR", sequenceName = "STATUS_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "statusDate")
   private java.util.Date statusDate;

   public Status()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.util.Date getStatusDate()
   {
      return this.statusDate;
   }

   public void setStatusDate(java.util.Date statusDate)
   {
      this.statusDate = statusDate;
   }

   public Status(java.lang.Long id, java.lang.String status,
         java.util.Date statusDate)
   {
      this.id = id;
      this.status = status;
      this.statusDate = statusDate;
   }

}